In [1]:
import pandas as pd

In [2]:
matches = pd.read_csv("matches.csv", index_col=0)

In [3]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2.0,0.0,West Ham,...,Match Report,NaN,13.0,1.0,18.7,1.0,1.0,1.0,2022,Manchester City
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,0.0,Bournemouth,...,Match Report,NaN,19.0,7.0,17.5,0.0,0.0,0.0,2022,Manchester City
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3.0,3.0,Newcastle Utd,...,Match Report,NaN,21.0,10.0,16.2,1.0,0.0,0.0,2022,Manchester City
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,2.0,Crystal Palace,...,Match Report,NaN,18.0,5.0,14.1,0.0,0.0,0.0,2022,Manchester City
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6.0,0.0,Nott'ham Forest,...,Match Report,NaN,17.0,9.0,14.8,0.0,0.0,0.0,2022,Manchester City

In [4]:
matches.shape

(1454, 27)

In [5]:
matches["team"].value_counts() # checking count

Crystal Palace              73
Wolverhampton Wanderers     73
Southampton                 73
Leeds United                73
Liverpool                   73
Tottenham Hotspur           73
Leicester City              73
Aston Villa                 73
Brentford                   73
Everton                     73
West Ham United             73
Arsenal                     73
Manchester City             72
Chelsea                     72
Manchester United           72
Newcastle United            72
Brighton and Hove Albion    71
Burnley                     38
Watford                     38
Norwich City                38
Bournemouth                 35
Nottingham Forest           35
Fulham                      35
Name: team, dtype: int64

In [6]:
matches[matches["team"] == "Liverpool"]

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2022-08-06,12:30,Premier League,Matchweek 1,Sat,Away,D,2.0,2.0,Fulham,...,Match Report,NaN,11.0,3.0,12.4,0.0,0.0,0.0,2022,Liverpool
2,2022-08-15,20:00,Premier League,Matchweek 2,Mon,Home,D,1.0,1.0,Crystal Palace,...,Match Report,NaN,24.0,4.0,17.4,0.0,0.0,0.0,2022,Liverpool
3,2022-08-22,20:00,Premier League,Matchweek 3,Mon,Away,L,1.0,2.0,Manchester Utd,...,Match Report,NaN,17.0,5.0,14.4,0.0,0.0,0.0,2022,Liverpool
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,9.0,0.0,Bournemouth,...,Match Report,NaN,19.0,12.0,11.6,0.0,0.0,0.0,2022,Liverpool
5,2022-08-31,20:00,Premier League,Matchweek 5,Wed,Home,W,2.0,1.0,Newcastle Utd,...,Match Report,NaN,23.0,6.0,17.8,0.0,0.0,0.0,2022,Liverpool
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55,2022-04-30,12:30,Premier League,Matchweek 35,Sat,Away,W,1.0,0.0,Newcastle Utd,...,Match Report,NaN,24.0,10.0,17.7,2.0,0.0,0.0,2021,Liverpool
57,2022-05-07,19:45,Premier League,Matchweek 36,Sat,Home,D,1.0,1.0,Tottenham,...,Match Report,NaN,22.0,3.0,19.6,1.0,0.0,0.0,2021,Liverpool
58,2022-05-10,20:00,Premier League,Matchweek 33,Tue,Away,W,2.0,1.0,Aston Villa,...,Match Report,NaN,17.0,5.0,17.0,2.0,0.0,0.0,2021,Liverpool
60,2022-05-17,19:45,Premier League,Matchweek 37,Tue,Away,W,2.0,1.0,Southampton,...,Match Report,NaN,24.0,5.0,18.6,0.0,0.0,0.0,2021,Liverpool
61,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,W,3.0,1.0,Wolves,...,Match Report,NaN,29.0,7.0,15.6,0.0,0.0,0.0,2021,Liverpool

In [7]:
matches["round"].value_counts()

Matchweek 1     40
Matchweek 27    40
Matchweek 2     40
Matchweek 22    40
Matchweek 23    40
Matchweek 12    40
Matchweek 24    40
Matchweek 26    40
Matchweek 29    40
Matchweek 20    40
Matchweek 30    40
Matchweek 31    40
Matchweek 33    40
Matchweek 34    40
Matchweek 28    40
Matchweek 35    40
Matchweek 7     40
Matchweek 21    40
Matchweek 19    40
Matchweek 10    40
Matchweek 3     40
Matchweek 4     40
Matchweek 5     40
Matchweek 6     40
Matchweek 8     40
Matchweek 18    40
Matchweek 9     40
Matchweek 11    40
Matchweek 13    40
Matchweek 14    40
Matchweek 15    40
Matchweek 16    40
Matchweek 17    40
Matchweek 25    38
Matchweek 32    36
Matchweek 36    20
Matchweek 37    20
Matchweek 38    20
Name: round, dtype: int64

In [8]:
matches.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf              float64
ga              float64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk              float64
pkatt           float64
season            int64
team             object
dtype: object

In [9]:
matches["date"] = pd.to_datetime(matches["date"])

# PREDICTORS

In [10]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes #creating venue

In [11]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes #creating unique codes

In [12]:
matches["hour"] = matches["time"].str.replace(":.+","", regex=True).astype("int")

In [13]:
matches["day_code"] = matches["date"].dt.dayofweek

In [14]:
matches["target"] = (matches["result"] =="W").astype("int")

In [15]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2.0,0.0,West Ham,...,1.0,1.0,1.0,2022,Manchester City,0,21,16,6,1
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,0.0,Bournemouth,...,0.0,0.0,0.0,2022,Manchester City,1,2,15,5,1
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3.0,3.0,Newcastle Utd,...,1.0,0.0,0.0,2022,Manchester City,0,15,16,6,0
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,2.0,Crystal Palace,...,0.0,0.0,0.0,2022,Manchester City,1,7,15,5,1
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6.0,0.0,Nott'ham Forest,...,0.0,0.0,0.0,2022,Manchester City,1,17,19,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2022-04-30,15:00,Premier League,Matchweek 35,Sat,Away,L,0.0,2.0,Aston Villa,...,0.0,0.0,0.0,2021,Norwich City,0,1,15,5,0
39,2022-05-08,14:00,Premier League,Matchweek 36,Sun,Home,L,0.0,4.0,West Ham,...,1.0,0.0,0.0,2021,Norwich City,1,21,14,6,0
40,2022-05-11,19:45,Premier League,Matchweek 21,Wed,Away,L,0.0,3.0,Leicester City,...,0.0,0.0,0.0,2021,Norwich City,0,11,19,2,0
41,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,1.0,1.0,Wolves,...,0.0,0.0,0.0,2021,Norwich City,0,22,14,6,0
42,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,L,0.0,5.0,Tottenham,...,0.0,0.0,0.0,2021,Norwich City,1,19,16,6,0

# ML MODEL

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [17]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [18]:
train = matches[matches["date"] < "2022-01-01"]

In [19]:
test = matches[matches["date"] > "2022-01-01"]

In [20]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [21]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [22]:
preds= rf.predict(test[predictors]) # passing test data and predictors

In [23]:
from sklearn.metrics import accuracy_score # checking the accuracy off the model

In [24]:
error = accuracy_score(test["target"], preds)

In [25]:
error

0.5942698706099815

In [26]:
combined = pd.DataFrame(dict(actual=test["target"], prediction = preds))

In [27]:
pd.crosstab(index=combined["actual"], columns = combined["prediction"])

prediction    0    1
actual
0           509  148
1           291  134

In [28]:
from sklearn.metrics import precision_score

In [29]:
 precision_score(test["target"], preds)

0.475177304964539

In [30]:
grouped_matches = matches.groupby("team")

In [31]:
group = grouped_matches.get_group("Manchester City")

In [32]:
 group

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2.0,0.0,West Ham,...,1.0,1.0,1.0,2022,Manchester City,0,21,16,6,1
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,0.0,Bournemouth,...,0.0,0.0,0.0,2022,Manchester City,1,2,15,5,1
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3.0,3.0,Newcastle Utd,...,1.0,0.0,0.0,2022,Manchester City,0,15,16,6,0
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,2.0,Crystal Palace,...,0.0,0.0,0.0,2022,Manchester City,1,7,15,5,1
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6.0,0.0,Nott'ham Forest,...,0.0,0.0,0.0,2022,Manchester City,1,17,19,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,2022-04-30,17:30,Premier League,Matchweek 35,Sat,Away,W,4.0,0.0,Leeds United,...,0.0,0.0,0.0,2021,Manchester City,0,10,17,5,1
54,2022-05-08,16:30,Premier League,Matchweek 36,Sun,Home,W,5.0,0.0,Newcastle Utd,...,1.0,0.0,0.0,2021,Manchester City,1,15,16,6,1
55,2022-05-11,20:15,Premier League,Matchweek 33,Wed,Away,W,5.0,1.0,Wolves,...,0.0,0.0,0.0,2021,Manchester City,0,22,20,2,1
56,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,2.0,2.0,West Ham,...,2.0,0.0,1.0,2021,Manchester City,0,21,14,6,0
57,2022-05-22,16:00,Premier League,Matchweek 38,Sun,Home,W,3.0,2.0,Aston Villa,...,1.0,0.0,0.0,2021,Manchester City,1,1,16,6,1

In [33]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed = "left").mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset = new_cols)
    return group

In [34]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

In [35]:
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling']

In [36]:
rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,5,1,3.333333,0.333333,19.666667,6.000000,16.866667,0.666667,0.000000,0.000000
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,5,0,3.666667,0.000000,22.000000,7.333333,15.866667,0.333333,0.000000,0.000000
8,2021-09-25,12:30,Premier League,Matchweek 6,Sat,Away,W,1.0,0.0,Chelsea,...,5,1,2.000000,0.000000,22.000000,6.333333,15.166667,0.333333,0.000000,0.000000
10,2021-10-03,16:30,Premier League,Matchweek 7,Sun,Away,D,2.0,2.0,Liverpool,...,6,0,0.666667,0.000000,18.666667,4.000000,15.933333,0.333333,0.000000,0.000000
11,2021-10-16,15:00,Premier League,Matchweek 8,Sat,Home,W,2.0,0.0,Burnley,...,5,1,1.000000,0.666667,14.333333,2.333333,16.833333,0.666667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46,2023-04-15,17:30,Premier League,Matchweek 31,Sat,Home,W,3.0,1.0,Leicester City,...,5,1,3.000000,0.666667,14.000000,6.000000,15.566667,0.666667,0.666667,0.666667
49,2023-04-26,20:00,Premier League,Matchweek 33,Wed,Home,W,4.0,1.0,Arsenal,...,2,1,3.666667,1.000000,13.333333,6.000000,15.166667,0.333333,0.666667,0.666667
50,2023-04-30,14:00,Premier League,Matchweek 34,Sun,Away,W,2.0,1.0,Fulham,...,6,1,3.666667,1.000000,12.333333,6.333333,15.633333,0.000000,0.666667,0.666667
51,2023-05-03,20:00,Premier League,Matchweek 28,Wed,Home,W,3.0,0.0,West Ham,...,2,1,3.000000,1.000000,12.000000,6.666667,15.933333,0.000000,0.666667,0.666667
52,2023-05-06,15:00,Premier League,Matchweek 35,Sat,Home,W,2.0,1.0,Leeds United,...,5,1,3.000000,0.666667,13.666667,8.000000,15.433333,0.000000,0.333333,0.333333

In [37]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [38]:
matches_rolling

                                 date   time            comp         round  \
team
Arsenal                 4  2021-09-11  15:00  Premier League   Matchweek 4
                        5  2021-09-18  15:00  Premier League   Matchweek 5
                        7  2021-09-26  16:30  Premier League   Matchweek 6
                        8  2021-10-02  17:30  Premier League   Matchweek 7
                        9  2021-10-18  20:00  Premier League   Matchweek 8
...                               ...    ...             ...           ...
Wolverhampton Wanderers 36 2023-04-15  15:00  Premier League  Matchweek 31
                        37 2023-04-22  15:00  Premier League  Matchweek 32
                        38 2023-04-25  19:30  Premier League  Matchweek 33
                        39 2023-04-29  15:00  Premier League  Matchweek 34
                        40 2023-05-06  15:00  Premier League  Matchweek 35

                            day venue result   gf   ga        opponent  ...  \
team                                                                    ...
Arsenal                 4   Sat  Home      W  1.0  0.0    Norwich City  ...
                        5   Sat  Away      W  1.0  0.0         Burnley  ...
                        7   Sun  Home      W  3.0  1.0       Tottenham  ...
                        8   Sat  Away      D  0.0  0.0        Brighton  ...
                        9   Mon  Home      D  2.0  2.0  Crystal Palace  ...
...                         ...   ...    ...  ...  ...             ...  ...
Wolverhampton Wanderers 36  Sat  Home      W  2.0  0.0       Brentford  ...
                        37  Sat  Away      L  1.0  2.0  Leicester City  ...
                        38  Tue  Home      W  2.0  0.0  Crystal Palace  ...
                        39  Sat  Away      L  0.0  6.0        Brighton  ...
                        40  Sat  Home      W  1.0  0.0     Aston Villa  ...

                            day_code  target  gf_rolling  ga_rolling  \
team
Arsenal                 4          5       1    0.000000    3.000000
                        5          5       1    0.333333    2.333333
                        7          6       1    0.666667    1.666667
                        8          5       0    1.666667    0.333333
                        9          0       0    1.333333    0.333333
...                              ...     ...         ...         ...
Wolverhampton Wanderers 36         5       1    1.333333    1.666667
                        37         5       0    1.333333    0.333333
                        38         1       1    1.333333    0.666667
                        39         5       0    1.666667    0.666667
                        40         5       1    1.000000    2.666667

                           sh_rolling sot_rolling dist_rolling fk_rolling  \
team
Arsenal                 4    9.666667    2.333333    14.833333   0.333333
                        5   12.333333    3.000000    14.133333   0.333333
                        7   14.666667    3.000000    14.800000   0.666667
                        8   18.333333    5.333333    18.433333   0.666667
                        9   11.000000    4.000000    19.833333   0.666667
...                               ...         ...          ...        ...
Wolverhampton Wanderers 36  13.333333    4.333333    19.166667   0.333333
                        37   9.333333    4.666667    19.933333   0.000000
                        38  12.000000    5.333333    21.100000   0.666667
                        39  11.666667    4.666667    18.700000   0.666667
                        40  11.333333    2.333333    18.800000   0.666667

                            pk_rolling  pkatt_rolling
team
Arsenal                 4     0.000000       0.000000
                        5     0.000000       0.000000
                        7     0.000000       0.000000
                        8     0.000000       0.000000
                        9     0.000000       0.000000
...                                ...            ...
Wolverhampton Wanderers 36    0.000000       0.000000
                        37    0.000000       0.000000
                        38    0.000000       0.000000
                        39    0.333333       0.333333
                        40    0.333333       0.333333

[1385 rows x 40 columns]

In [39]:
matches_rolling = matches_rolling.droplevel("team")

In [40]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Home,W,1.0,0.0,Norwich City,...,5,1,0.000000,3.000000,9.666667,2.333333,14.833333,0.333333,0.000000,0.000000
5,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Away,W,1.0,0.0,Burnley,...,5,1,0.333333,2.333333,12.333333,3.000000,14.133333,0.333333,0.000000,0.000000
7,2021-09-26,16:30,Premier League,Matchweek 6,Sun,Home,W,3.0,1.0,Tottenham,...,6,1,0.666667,1.666667,14.666667,3.000000,14.800000,0.666667,0.000000,0.000000
8,2021-10-02,17:30,Premier League,Matchweek 7,Sat,Away,D,0.0,0.0,Brighton,...,5,0,1.666667,0.333333,18.333333,5.333333,18.433333,0.666667,0.000000,0.000000
9,2021-10-18,20:00,Premier League,Matchweek 8,Mon,Home,D,2.0,2.0,Crystal Palace,...,0,0,1.333333,0.333333,11.000000,4.000000,19.833333,0.666667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36,2023-04-15,15:00,Premier League,Matchweek 31,Sat,Home,W,2.0,0.0,Brentford,...,5,1,1.333333,1.666667,13.333333,4.333333,19.166667,0.333333,0.000000,0.000000
37,2023-04-22,15:00,Premier League,Matchweek 32,Sat,Away,L,1.0,2.0,Leicester City,...,5,0,1.333333,0.333333,9.333333,4.666667,19.933333,0.000000,0.000000,0.000000
38,2023-04-25,19:30,Premier League,Matchweek 33,Tue,Home,W,2.0,0.0,Crystal Palace,...,1,1,1.333333,0.666667,12.000000,5.333333,21.100000,0.666667,0.000000,0.000000
39,2023-04-29,15:00,Premier League,Matchweek 34,Sat,Away,L,0.0,6.0,Brighton,...,5,0,1.666667,0.666667,11.666667,4.666667,18.700000,0.666667,0.333333,0.333333
40,2023-05-06,15:00,Premier League,Matchweek 35,Sat,Home,W,1.0,0.0,Aston Villa,...,5,1,1.000000,2.666667,11.333333,2.333333,18.800000,0.666667,0.333333,0.333333

In [41]:
matches_rolling.index = range(matches_rolling.shape[0])

In [42]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Home,W,1.0,0.0,Norwich City,...,5,1,0.000000,3.000000,9.666667,2.333333,14.833333,0.333333,0.000000,0.000000
1,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Away,W,1.0,0.0,Burnley,...,5,1,0.333333,2.333333,12.333333,3.000000,14.133333,0.333333,0.000000,0.000000
2,2021-09-26,16:30,Premier League,Matchweek 6,Sun,Home,W,3.0,1.0,Tottenham,...,6,1,0.666667,1.666667,14.666667,3.000000,14.800000,0.666667,0.000000,0.000000
3,2021-10-02,17:30,Premier League,Matchweek 7,Sat,Away,D,0.0,0.0,Brighton,...,5,0,1.666667,0.333333,18.333333,5.333333,18.433333,0.666667,0.000000,0.000000
4,2021-10-18,20:00,Premier League,Matchweek 8,Mon,Home,D,2.0,2.0,Crystal Palace,...,0,0,1.333333,0.333333,11.000000,4.000000,19.833333,0.666667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1380,2023-04-15,15:00,Premier League,Matchweek 31,Sat,Home,W,2.0,0.0,Brentford,...,5,1,1.333333,1.666667,13.333333,4.333333,19.166667,0.333333,0.000000,0.000000
1381,2023-04-22,15:00,Premier League,Matchweek 32,Sat,Away,L,1.0,2.0,Leicester City,...,5,0,1.333333,0.333333,9.333333,4.666667,19.933333,0.000000,0.000000,0.000000
1382,2023-04-25,19:30,Premier League,Matchweek 33,Tue,Home,W,2.0,0.0,Crystal Palace,...,1,1,1.333333,0.666667,12.000000,5.333333,21.100000,0.666667,0.000000,0.000000
1383,2023-04-29,15:00,Premier League,Matchweek 34,Sat,Away,L,0.0,6.0,Brighton,...,5,0,1.666667,0.666667,11.666667,4.666667,18.700000,0.666667,0.333333,0.333333
1384,2023-05-06,15:00,Premier League,Matchweek 35,Sat,Home,W,1.0,0.0,Aston Villa,...,5,1,1.000000,2.666667,11.333333,2.333333,18.800000,0.666667,0.333333,0.333333

# Retrainig our machine learining model

In [43]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2022-01-01']
    test = data[data["date"] > '2022-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    error = precision_score(test["target"], preds)
    return combined, error

In [44]:
combined, precision = make_predictions(matches_rolling, predictors + new_cols)

In [45]:
precision

0.5022421524663677

In [46]:
combined = combined.merge(matches_rolling [["date","team","opponent","result"]], left_index = True, right_index = True)

In [47]:
combined

,actual,predicted,date,team,opponent,result
17,0,0,2022-01-23,Arsenal,Burnley,D
18,1,0,2022-02-10,Arsenal,Wolves,W
19,1,0,2022-02-19,Arsenal,Brentford,W
20,1,1,2022-02-24,Arsenal,Wolves,W
21,1,1,2022-03-06,Arsenal,Watford,W
...,...,...,...,...,...,...
1380,1,0,2023-04-15,Wolverhampton Wanderers,Brentford,W
1381,0,0,2023-04-22,Wolverhampton Wanderers,Leicester City,L
1382,1,0,2023-04-25,Wolverhampton Wanderers,Crystal Palace,W
1383,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L
1384,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W

# combinig both Home and Away teams

In [48]:
class MissingDict(dict):
    __missing__ = lambda self, key: key
    
map_values = {"Brighton and Hove Albion": "Brighton",
              "Manchester United": "Manchester Utd",
              "Newcastle United": "Newcastle Utd",
              "Tottenham Hotspur": "Tottenham",
              "West Ham United": "West Ham",
              "Wolverhampton Wanderers": "Wolves"} 

mapping = MissingDict(**map_values)

In [49]:
combined["new_team"] = combined["team"].map(mapping)

In [50]:
combined

,actual,predicted,date,team,opponent,result,new_team
17,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal
18,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal
19,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal
20,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal
21,1,1,2022-03-06,Arsenal,Watford,W,Arsenal
...,...,...,...,...,...,...,...
1380,1,0,2023-04-15,Wolverhampton Wanderers,Brentford,W,Wolves
1381,0,0,2023-04-22,Wolverhampton Wanderers,Leicester City,L,Wolves
1382,1,0,2023-04-25,Wolverhampton Wanderers,Crystal Palace,W,Wolves
1383,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L,Wolves
1384,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W,Wolves

In [51]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [52]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,0,2022-01-23,Arsenal,Burnley,D,Arsenal,0,0,Burnley,Arsenal,D,Burnley
1,1,0,2022-02-10,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
2,1,0,2022-02-19,Arsenal,Brentford,W,Arsenal,0,0,Brentford,Arsenal,L,Brentford
3,1,1,2022-02-24,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
4,1,1,2022-03-06,Arsenal,Watford,W,Arsenal,0,0,Watford,Arsenal,L,Watford
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027,1,0,2023-04-15,Wolverhampton Wanderers,Brentford,W,Wolves,0,0,Brentford,Wolves,L,Brentford
1028,0,0,2023-04-22,Wolverhampton Wanderers,Leicester City,L,Wolves,1,0,Leicester City,Wolves,W,Leicester City
1029,1,0,2023-04-25,Wolverhampton Wanderers,Crystal Palace,W,Wolves,0,0,Crystal Palace,Wolves,L,Crystal Palace
1030,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L,Wolves,1,1,Brighton and Hove Albion,Wolves,W,Brighton
1031,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W,Wolves,0,0,Aston Villa,Wolves,L,Aston Villa

In [53]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] == 0)]["actual_x"].value_counts()

1    95
0    84
Name: actual_x, dtype: int64

In [55]:
95/179

0.5307262569832403